#!/usr/bin/env python
#
# Reads in an XHTML+RDFa file and outputs the triples generated by the file
# in N3 format.
import sys, os
sys.path += ("../python/dist/linux",)
import rdfa

def ht():
    print "Triple found!"

def fb(dataFile, bufferSize):
    rval = dataFile.read(bufferSize)
    print "Fill buffer --- (%i)" % (bufferSize,)

##    for i in range(1, 100):
##        print "IPREAD %i" % (i,)
##    if(len(gInputData[gOffset:]) > bufferSize):
##        rval = gInputData[gOffset:gOffset + buffer_size]
##        gOffset = gOffset + buffer_size
##    else:
##        rval = gInputData[gOffset:]
##        gOffset = gOffset + len(rval)
        
#    rval = gInputFile.read(buffer_size)
##    rval = """<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n
##    <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML+RDFa 1.0//EN\"
##    \"http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd\">\n
##    <html xmlns=\"http://www.w3.org/1999/xhtml\"\n
##          xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n
##    <head><title>Speed Test</title></head>\n
##    <body><p>\n"""

##    for i in range(1, 20):
##        rval += "<span about=\"#foo\" rel=\"dc:title\" resource=\"#you\" />"

##    rval += """</p></body></html>"""
    
    print "IPFINISH"

    print "DATA:", rval, len(rval)
    print "\n\n\n"
    
    return rval

##
# The main entry point for the script.
#
# @param argv the argument list passed to the program.
# @param stdout the standard output stream assigned to the program.
# @param environ the execution environment for the program.
def main(argv, stdout, environ):
    print "creating parser"
    parser = rdfa.RdfaParser("http://www.w3.org/2006/07/SWD/RDFa/testsuite/xhtml1-testcases/0001.xhtml")

    print "opening", argv[1]
    dataFile = open(argv[1], "r")
    
    print "created parser"
    parser.setTripleHandler(ht)
    print "set triple handler"
    parser.setBufferHandler(fb, dataFile)
    print "set buffer handler"

    print "parsing..."
    parser.parse()
    print "completed parsing"
    dataFile.close()
    
##
# Run the rdfa2n3 python application.
if __name__ == "__main__":
    main(sys.argv, sys.stdout, os.environ)
