#!/usr/bin/env python
#
# Reads in an XHTML+RDFa file and outputs the triples generated by the file
# in N3 format.
import sys, os
sys.path += ("../python/dist/linux",)
import rdfa

##
# The triple processor class is responsible for feeding the RDFa parser
# and collecting triples that are generated by the RDFa parser.
class TripleProcessor:
    def __init__(self, inputFile):
        self.dataStream = open(inputFile, "r")
        
    def handleTriple(self, triple):
        print "Triple found!"

    def fillBuffer(self, bufferSize):
        print "Fill buffer"
        return ""

def ht():
    print "Triple found!"


def fb():
    print "Fill buffer"

##
# The main entry point for the script.
#
# @param argv the argument list passed to the program.
# @param stdout the standard output stream assigned to the program.
# @param environ the execution environment for the program.
def main(argv, stdout, environ):
    tp = TripleProcessor("testsuite/0001.xhtml")
    parser = rdfa.RdfaParser("http://example.com/foo.xhtml")
    print "FOO!"
    parser.setTripleHandler(ht)
    parser.setBufferHandler(fb)
    parser.parse()

##
# Run the rdfa2n3 python application.
if __name__ == "__main__":
    main(sys.argv, sys.stdout, os.environ)
